# Generated by Django 5.2.13 on 2026-05-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key_hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'workspace',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor')], default='editor', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to='core.account')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workspace')),
            ],
            options={
                'db_table': 'workspace_membership',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'account'), name='uniq_workspace_membership_account'), models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('account',), name='uniq_owner_membership_per_account'), models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('workspace',), name='uniq_one_owner_per_workspace')],
            },
        ),
    ]
