# Generated by Django 5.2.13 on 2026-05-12 17:01

import core.entities.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitemedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontentslot',
            options={'ordering': ['key', 'id']},
        ),
        migrations.AlterField(
            model_name='sitemedia',
            name='file',
            field=models.ImageField(max_length=500, upload_to=core.entities.sites.models.site_media_upload_to),
        ),
    ]
