# Generated by Django 5.2.13 on 2026-05-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitecontentslot_entry_and_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('short_name', models.CharField(blank=True, default='', max_length=20)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('canonical_url', models.URLField(blank=True, default='', max_length=500)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('title_template', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('robots_index', models.BooleanField(default=True)),
                ('twitter_handle', models.CharField(blank=True, default='', max_length=64)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('contact_address', models.TextField(blank=True, default='')),
                ('contact_region', models.CharField(blank=True, default='', max_length=200)),
                ('contact_consent_text', models.TextField(blank=True, default='')),
                ('contact_topics', models.JSONField(blank=True, default=list)),
                ('social_facebook', models.URLField(blank=True, default='', max_length=500)),
                ('social_x', models.URLField(blank=True, default='', max_length=500)),
                ('social_instagram', models.URLField(blank=True, default='', max_length=500)),
                ('social_linkedin', models.URLField(blank=True, default='', max_length=500)),
                ('social_youtube', models.URLField(blank=True, default='', max_length=500)),
                ('social_whatsapp', models.URLField(blank=True, default='', max_length=500)),
                ('nav_links', models.JSONField(blank=True, default=list)),
                ('nav_cta_label', models.CharField(blank=True, default='', max_length=64)),
                ('nav_cta_path', models.CharField(blank=True, default='', max_length=200)),
                ('html_lang', models.CharField(blank=True, default='en', max_length=16)),
                ('og_locale', models.CharField(blank=True, default='', max_length=16)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('date_format', models.CharField(blank=True, default='', max_length=32)),
                ('primary_color', models.CharField(blank=True, default='', max_length=20)),
                ('accent_color', models.CharField(blank=True, default='', max_length=20)),
                ('heading_font', models.CharField(blank=True, default='', max_length=100)),
                ('body_font', models.CharField(blank=True, default='', max_length=100)),
                ('analytics_id', models.CharField(blank=True, default='', max_length=120)),
                ('maintenance_enabled', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='')),
                ('copyright_name', models.CharField(blank=True, default='', max_length=200)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sitemedia')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sitemedia')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sitemedia')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.site')),
            ],
            options={
                'db_table': 'site_profile',
            },
        ),
    ]
